# Workspace is the root directory of all working subdirectories of the node. Please reserve at least 16 GiB of storage space for it.
WorkSpace: "./cacher"
# CacheSize: 17179869184 #default 16GB
# The RPC address of the blockchain where the cache protocol smart contract is deployed, usually the CESS chain
Rpcs: 
  - "wss://testnet-rpc.cess.cloud/ws/"
# SecretKey is the key of the node working account (Ethereum wallet account), which is used to initiate a call request to the cache protocol contract (working on EVM). 
# By default, it is not filled in, which means that it does not participate in the CD2N network and only has the most basic data interaction with the gateway.
SecretKey: ""
# Token is the NFT access certificate for nodes to join the CD2N network and will be released in subsequent versions.
Token: ""
# TokenAcc is the holder account(Ethereum wallet account) of the above NFT token.
TokenAcc: ""
# TokenAccSign is an Ethereum account signature, which is the token holder's proof of holding the token. 
# Signature methods and tools will be published in the document.
TokenAccSign: ""
# CD2N cache protocol contract address, which is responsible for node traffic statistics and reward distribution, and works on EVM.
ProtoContract: "0xce078A9098dF68189Cbe7A42FC629A4bDCe7dDD4"
# Local storage nodes configuration file, currently only available for the "Cess Multi-Miner Admin" script.
# The cacher automatically imports the storage node information started by the script through it.
MinerConfigPath: "/opt/cess/mineradm/config.yaml"
# You can manually configure the following connection options to make the cacher serve the specified retriever node:
# By default, it points to the CESS official retriever node. 
# If you register your cacher to the cache protocol contract, 
# it will automatically connect to some publicly available retriever nodes to get more opportunities to get rewards.
CdnNodes:
  - Account: "0xb7B43408864aEa0449D8F813380f8ec424F7a775" 
    Endpoint: "http://154.194.34.195:1306" 

# You can also manually import storage nodes through the following configuration. 
# The cacher will automatically check the availability of the storage node and complete other information from the chain.
# StorageNodes:
#   - Account: ""  # CESS account address
#     Endpoint: "" # Http address
